apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: rikkichahal/practice:${{ steps.extract-number.outputs.tag }}
      #imagePullPolicy: Always
      ports:
        - containerPort: 80
