apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: rikkichahal/practice:$IMAGE_TAG
      #imagePullPolicy: Always
      ports:
        - containerPort: 80
